[project]
name = "elevo"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "astropy>=8.0.1",
    "astrospice>=0.2.1",
    "cdflib>=1.3.12",
    "ialirt-data-access>=0.10.0",
    "matplotlib>=3.11.1",
    "multiprocess>=0.70.19",
    "netcdf4>=1.7.4",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "spacepy>=0.7.0",
    "spiceypy>=8.2.0",
    "sunpy>=7.0.5",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
